---
title: "My english activity log"
---

**11/10/2019**  

* I watched series on Netflix ( Mindhunter, Peaky Blinders )
* I worked on my presentation about Jellyfish and their attack system. 
* I read some articles about birds for my portfolio.

**13/10/2019**

* I watched a video on youtube about the attack of jellyfish.
<https://www.youtube.com/watch?v=7WJCnC5ebf4&t=1s>

**14/10/2019**

* I read the first article for my portfolio about birds.
* I used some websites for vocabulary.
* I watched one serie on Netflix.

**15/10/2019**

* I finished the analysis of my article.
* I wrote my presentation about Jellyfish.

**16/10/2019**

* I watched series on Netflix.
* I watched a video about the declin of birds.
<https://www.youtube.com/watch?v=Jps8ZkStK2Q>

**17/10/2019**

* I read the first article on Aurelie Pinchart's blog.
* I worked on my presentation of Jellyfish with this article: <https://www.weforum.org/agenda/2019/01/how-an-explosion-of-jellyfish-is-wreaking-havoc/>

**18/10/19**

* I watched a lot of videos about marine animals:
<https://www.youtube.com/watch?v=9z8ujpPgUjI&t=16s>, <https://www.youtube.com/watch?v=0wtLrlIKvJE>, <https://www.youtube.com/watch?v=dKWssIQplw8>, <https://www.youtube.com/watch?v=7OZhnXCtuGY> 
* I finished my text about jellyfish.

**19/10/19**

* I red this article about Eutrophication: <https://www.nature.com/scitable/knowledge/library/eutrophication-causes-consequences-and-controls-in-aquatic-102364466/>
* I watched *Mindhunter* on Netflix.
* I read my second article for my portfolio.

**20/10/2019**

* I worked on my second article for my portfolio.
* I trained for my oral presentation on jellyfish.
* I watched *Minhunter* on Netflix. 
* I read the first article about koalas on Adrien Roulez's blog. 

**24/10/2019**

* I read some articles about birds.
* I watched series on Netflix.
