---
title: "My english activity log"
description: |
  This post represents all of my English activities. (series, videos, articles, homework, ...)
author:
  - name: Olivieri Maria-Louisa
    url: {}
date: 12-09-2019
preview: english.jpg
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### **11/10/2019**  

* I watched series on Netflix ( Mindhunter, Peaky Blinders )
* I worked on my presentation about Jellyfish and their attack system. 
* I read some articles about birds for my portfolio.

### **13/10/2019**

* I watched a video on youtube about the attack of jellyfish.
<https://www.youtube.com/watch?v=7WJCnC5ebf4&t=1s>

### **14/10/2019**

* I read the first article for my portfolio about birds.
* I used some websites for vocabulary.
* I watched one serie on Netflix.

### **15/10/2019**

* I finished the analysis of my article.
* I wrote my presentation about Jellyfish.

### **16/10/2019**

* I watched series on Netflix.
* I watched a video about the declin of birds.
<https://www.youtube.com/watch?v=Jps8ZkStK2Q>

### **17/10/2019**

* I read the first article on Aurelie Pinchart's blog.
* I worked on my presentation of Jellyfish with this article: <https://www.weforum.org/agenda/2019/01/how-an-explosion-of-jellyfish-is-wreaking-havoc/>

### **18/10/19**

* I watched a lot of videos about marine animals:
<https://www.youtube.com/watch?v=9z8ujpPgUjI&t=16s>, <https://www.youtube.com/watch?v=0wtLrlIKvJE>, <https://www.youtube.com/watch?v=dKWssIQplw8>, <https://www.youtube.com/watch?v=7OZhnXCtuGY> 
* I finished my text about jellyfish.

### **19/10/19**

* I red this article about Eutrophication: <https://www.nature.com/scitable/knowledge/library/eutrophication-causes-consequences-and-controls-in-aquatic-102364466/>
* I watched *Mindhunter* on Netflix.
* I read my second article for my portfolio.

### **20/10/2019**

* I worked on my second article for my portfolio.
* I trained for my oral presentation on jellyfish.
* I watched *Minhunter* on Netflix. 
* I read the first article about koalas on Adrien Roulez's blog. 

### **24/10/2019**

* I read some articles about birds.
* I watched series on Netflix.

### **25/10/2019**

* I made my vocabulary on the second article of my portfolio.
* I read this article about jellyfish: <https://www.rd.com/culture/weirdly-fascinating-jellyfish-facts/> 
* I watched *Minhunter* on Netflix.

### **27/10/2019**

* I watched *Mindhunter* on Netflix.
* I trained myself for my oral presentation on Jellyfish.

### **29/10/19**

* I worked on my third article for my portfolio.
* I watched biological videos on youtube.
* I practiced my oral on Jellyfish to train.

### **01/11/19**

* I worked on my second oral presentation about a famous monument: Washington Monument, with this article <https://www.newworldencyclopedia.org/entry/Washington_Monument>
* I trained for my oral on Jellyfish.

### **03/11/19**

* I trained again for my oral on Jellyfish in front of my mother.
* I watched this video about raptors: <https://www.youtube.com/watch?v=fnkV3S3aOio&t=171s>
* I watched *Peaky Blinders* on Netflix.
* I read this article about the immortal Jellyfish *Turritopsis dohrnii* <https://immortal-jellyfish.com>

### **05/11/19**

* I worked on my third article for my portfolio about birds from Australia.

### **10/11/19**

* I watched videos about *movies* on Youtube: <https://www.youtube.com/watch?v=qQ2UtHMtOZk>, <https://www.youtube.com/watch?v=nVRzCE7LmdI&t=35s>, <https://www.youtube.com/watch?v=Ga0rs2G8BGI&t=2s>

### **15/11/19**

* I worked on my presentation about the *Washington Monument*
* I watched some videos on youtube about Evolution.

### **17/11/19**

* I practiced my oral presentation.
* I read my fourth article for my portfolio.
* I watched a video about *diffusion* <https://www.youtube.com/watch?v=jhszFBtBPoI>

### **18/11/19**

* I watched the movie *Batman the Dark Knight* in English with English subtitle.

### **19/11/19**

* I watched a video for my Biochemistry lab <https://www.youtube.com/watch?v=yjLB_ntM324> 
* I watched a video about Biology <https://www.youtube.com/watch?v=wENhHnJI1ys&t=2s>

#### **22/11/19**

* I watched a video on youtube about cancer <https://www.youtube.com/watch?v=_QVO75CihYQ> 
* I read the first pages of the book *The rats in the walls*.

### **27/11/19**

* I watched the film *The Irishman* on *Netflix*.

### **10/12/19**

* I watched **Sugar rush** on Netflix.
* I read the book *The rats in the walls*.

### **13/12/19**

* I watched **V Wars** on *Netfix*.

